// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Character, CharacterData } from "./tables/Character.sol";
import { PlayerPrivateState } from "./tables/PlayerPrivateState.sol";
